In [3]:
import pandas as pd
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
ratings=pd.DataFrame(pd.read_excel("ultimatedata.xlsx",index_col=0))
ratings=ratings.fillna(0);
ratings

,abdul bari,bharat khana,jenny's,vivekanand,striver,errichto,gallen colin,priyansh agrawal,tushar roy,sandeep jain
student,,,,,,,,,,
bhaskar,9.0,8,6,0.0,10.0,3.0,6.0,5.0,1.0,8.0
ramesh,8.0,6,3,0.0,0.0,4.0,7.0,7.0,1.0,7.0
farhan,9.0,8,7,4.0,0.0,3.0,8.0,8.0,1.0,9.0
manhar,7.0,9,7,0.0,0.0,4.0,6.0,5.0,1.0,8.0
nishnat,8.0,8,4,7.0,0.0,3.0,7.0,9.0,1.0,7.0
belal,6.0,8,5,0.0,7.0,4.0,0.0,6.0,1.0,8.0
kamal,7.0,8,5,8.0,8.0,0.0,0.0,9.0,1.0,9.0
pratik,5.0,8,6,0.0,0.0,0.0,0.0,7.0,6.0,7.0
shahbaz,7.0,9,8,6.0,4.0,0.0,9.0,5.0,0.0,7.0
prince,8.0,10,9,5.0,9.0,0.0,0.0,9.0,0.0,7.0
shruti,6.0,8,4,8.0,7.0,5.0,3.0,4.0,0.0,7.0
prachi,8.0,7,4,0.0,9.0,0.0,0.0,8.0,0.0,7.0
pratyush,7.0,8,5,5.0,7.0,0.0,0.0,0.0,4.0,0.0
vishal,9.0,8,6,8.0,5.0,0.0,5.0,0.0,0.0,0.0
rahul,5.0,8,7,0.0,8.0,7.0,0.0,4.0,0.0,8.0
Shubham,8.0,8,7,4.0,9.0,0.0,0.0,9.0,0.0,8.0
rishav,6.0,8,4,8.0,6.0,0.0,7.0,0.0,0.0,8.0
sumit,9.0,9,8,4.0,8.0,8.0,0.0,4.0,0.0,6.0
bhupendra,8.0,5,8,9.0,6.0,0.0,0.0,0.0,4.0,8.0
Abhishek,8.0,4,8,10.0,8.0,0.0,9.0,8.0,0.0,0.0
naman,0.0,5,8,10.0,6.0,0.0,0.0,9.0,0.0,0.0
Ankit,9.0,3,6,10.0,8.0,0.0,2.0,3.0,0.0,8.0
Sumit,0.0,7,9,10.0,6.0,0.0,1.0,8.0,4.0,9.0
ishan,7.0,6,2,10.0,0.0,0.0,1.0,6.0,0.0,0.0
rishi,7.0,5,6,10.0,0.0,0.0,1.0,7.0,4.0,9.0
babul,7.0,7,6,10.0,8.0,5.0,0.0,4.0,4.0,9.0
rakesh,0.0,3,4,10.0,8.0,2.0,1.0,7.0,4.0,7.0
Shivani,0.0,5,4,10.0,0.0,2.0,6.0,7.0,4.0,9.0
shristi,8.0,5,4,10.0,8.0,2.0,8.0,7.0,1.0,0.0

In [6]:
def standardize(row):
    new_row=(row- row.mean())/ (row.max() - row.min());
    return new_row
ratings_std = ratings.apply(standardize)
ratings_std=ratings_std.fillna(0);
item_similarity=cosine_similarity(ratings_std.T)
print(item_similarity)

[[ 1.          0.31882608 -0.00908145 -0.30051287  0.09104641  0.08775859
   0.21413845 -0.23975336 -0.41941304 -0.06253106]
 [ 0.31882608  1.          0.22476675 -0.57110629  0.00371991  0.26582431
  -0.0282838  -0.06393468 -0.24187883  0.20584461]
 [-0.00908145  0.22476675  1.         -0.01774744  0.26416911 -0.05524136
  -0.13465279  0.05113887 -0.0125322   0.1143071 ]
 [-0.30051287 -0.57110629 -0.01774744  1.          0.03306819 -0.37793731
   0.04429321 -0.04707471  0.14516361 -0.26883195]
 [ 0.09104641  0.00371991  0.26416911  0.03306819  1.          0.02981702
  -0.33636681 -0.13021994 -0.27869576 -0.0753444 ]
 [ 0.08775859  0.26582431 -0.05524136 -0.37793731  0.02981702  1.
   0.01769439 -0.08243238 -0.13353401  0.26018654]
 [ 0.21413845 -0.0282838  -0.13465279  0.04429321 -0.33636681  0.01769439
   1.          0.00720734 -0.27250652 -0.12292671]
 [-0.23975336 -0.06393468  0.05113887 -0.04707471 -0.13021994 -0.08243238
   0.00720734  1.         -0.05979619  0.1290914 ]
 [-0.41941304 -0.24187883 -0.0125322   0.14516361 -0.27869576 -0.13353401
  -0.27250652 -0.05979619  1.          0.24098706]
 [-0.06253106  0.20584461  0.1143071  -0.26883195 -0.0753444   0.26018654
  -0.12292671  0.1290914   0.24098706  1.        ]]

In [9]:
item_similarity_df=pd.DataFrame(item_similarity,index=ratings.columns,columns=ratings.columns)
item_similarity_df

,abdul bari,bharat khana,jenny's,vivekanand,striver,errichto,gallen colin,priyansh agrawal,tushar roy,sandeep jain
abdul bari,1.000000,0.318826,-0.009081,-0.300513,0.091046,0.087759,0.214138,-0.239753,-0.419413,-0.062531
bharat khana,0.318826,1.000000,0.224767,-0.571106,0.003720,0.265824,-0.028284,-0.063935,-0.241879,0.205845
jenny's,-0.009081,0.224767,1.000000,-0.017747,0.264169,-0.055241,-0.134653,0.051139,-0.012532,0.114307
vivekanand,-0.300513,-0.571106,-0.017747,1.000000,0.033068,-0.377937,0.044293,-0.047075,0.145164,-0.268832
striver,0.091046,0.003720,0.264169,0.033068,1.000000,0.029817,-0.336367,-0.130220,-0.278696,-0.075344
errichto,0.087759,0.265824,-0.055241,-0.377937,0.029817,1.000000,0.017694,-0.082432,-0.133534,0.260187
gallen colin,0.214138,-0.028284,-0.134653,0.044293,-0.336367,0.017694,1.000000,0.007207,-0.272507,-0.122927
priyansh agrawal,-0.239753,-0.063935,0.051139,-0.047075,-0.130220,-0.082432,0.007207,1.000000,-0.059796,0.129091
tushar roy,-0.419413,-0.241879,-0.012532,0.145164,-0.278696,-0.133534,-0.272507,-0.059796,1.000000,0.240987
sandeep jain,-0.062531,0.205845,0.114307,-0.268832,-0.075344,0.260187,-0.122927,0.129091,0.240987,1.000000

In [10]:
def get_similar_teacher(teacher_name,user_rating):
    similar_score=item_similarity_df[teacher_name]*user_rating
    similar_score=similar_score.sort_values(ascending=False)
    return similar_score
print(get_similar_teacher("striver",4))

striver             4.000000
jenny's             1.056676
abdul bari          0.364186
vivekanand          0.132273
errichto            0.119268
bharat khana        0.014880
sandeep jain       -0.301378
priyansh agrawal   -0.520880
tushar roy         -1.114783
gallen colin       -1.345467
Name: striver, dtype: float64